# CIS 106 Python Tests
#
# References:
#   https://docs.github.com/en/free-pro-team@latest/actions
#   https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python

name: CIS 106 Python Tests

on: [push]

jobs:
  build:
    name: Run CIS 106 Python Tests
    runs-on: ubuntu-latest
    timeout-minutes: 1
    
    steps:
    - name: Copy repository
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Python packages
      run: |
        # install flake8, pytest, and any requirements.txt 
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test with pytest
      run: |
        pytest .github/workflows/
